### ISSUE TITLE
Error: Cannot read property 'length' of undefined in version 3.0.1

### ISSUE THREAD

**Issue by iamyoki** [sapegin/mrm#160]
## Reproduce:
```
yarn global add mrm

mrm
```
then errors:
```
success Installed "mrm@3.0.1" with binaries:
      - mrm
✨  Done in 13.24s.
 ~  mrm
/Users/yoki/.config/yarn/global/node_modules/mrm/bin/mrm.js:55
                throw err;
                ^

TypeError: Cannot read property 'length' of undefined
    at getTasksList (/Users/yoki/.config/yarn/global/node_modules/mrm/bin/mrm.js:211:38)
    at commandHelp (/Users/yoki/.config/yarn/global/node_modules/mrm/bin/mrm.js:188:5)
    at main (/Users/yoki/.config/yarn/global/node_modules/mrm/bin/mrm.js:73:3)
 ~  
```

**Comment by duluca** [comment]
Same issue with npm. The release seems to be broken.
